### ISSUE TITLE
[BUG] duckling.botpress.io entity extraction behaviour not the same as docker binary

### ISSUE THREAD

**Issue by charlescatta** [botpress/nlu#106]
The default botpress-hosted version of duckling has a different extraction behaviour than the version in botpress/server's official docker image, example:

When extracting phone number + time:

Utterance: `Call me on (034)-234-2019 on Sunday`

On the docker version:
<img width="468" alt="Screen Shot 2021-09-24 at 10 34 35 AM" src="https://user-images.githubusercontent.com/18604963/134683197-b85025e4-89a6-4d3d-a123-da18d8271ad7.png">

On the botpress-hosted duckling.botpress.io:
<img width="448" alt="Screen Shot 2021-09-24 at 10 36 35 AM" src="https://user-images.githubusercontent.com/18604963/134683524-ac6e87dd-19b4-4808-8964-dc44238d35de.png">

**Comment by franklevasseur** [comment]
Hi!

This bug is now fixed. Just try the following command:

```shell
curl -XPOST https://duckling.botpress.io/parse --data 'locale=en_GB&text=Call me on (034)-234-2019 on Sunday'
```

it will output:
```json
[
  {
    "body": "(034)-234-2019",
    "start": 11,
    "value": { "value": "0342342019", "type": "value" },
    "end": 25,
    "dim": "phone-number",
    "latent": false
  },
  {
    "body": "on Sunday",
    "start": 26,
    "value": {
      "values": [
        {
          "value": "2021-12-19T00:00:00.000-08:00",
          "grain": "day",
          "type": "value"
        },
        {
          "value": "2021-12-26T00:00:00.000-08:00",
          "grain": "day",
          "type": "value"
        },
        {
          "value": "2022-01-02T00:00:00.000-08:00",
          "grain": "day",
          "type": "value"
        }
      ],
      "value": "2021-12-19T00:00:00.000-08:00",
      "grain": "day",
      "type": "value"
    },
    "end": 35,
    "dim": "time",
    "latent": false
  }
]
```
