### ISSUE TITLE
NLU server always binds to port 3200

### ISSUE THREAD

**Issue by spg** [botpress/nlu#37]
Even if port 3200 is already used, the NLU server will still try to connect to it, and crash if the port is used:
![2021-05-24 at 7 53 AM](https://user-images.githubusercontent.com/892367/119504631-29aeb380-bd3a-11eb-844d-1a528fd576d1.png)

Solution: bind to another port (3201)?

**Comment by franklevasseur** [comment]
Hi @spg,

Sorry for the late reply! 

This issue is already being handled in Botpress with the help of `portfinder`, [right here](https://github.com/botpress/botpress/pull/5043).

I'll close the issue, but feel free to reopen if needed

François
