### ISSUE TITLE
Hi! How to generate the language server file *.bpe.model and *.bin, such as Chinese.Thanks!

### ISSUE THREAD

**Issue by wuguokai** [botpress/nlu#54]
Hi! How to generate the language *.bpe.model and *.bin file, such as Chinese.Thanks!
![image](https://user-images.githubusercontent.com/30334643/121620035-34887880-ca9c-11eb-9d3f-ea0c40f227df.png)

**Comment by franklevasseur** [comment]
Hi @wuguokai,

As you've probably noticed, we host few languages models and tokenizers models at [this URL](https://nyc3.digitaloceanspaces.com/botpress-public/embeddings/index.json). Supported languages are the following ones:

![image](https://user-images.githubusercontent.com/25970722/121902959-cdfe9700-ccf5-11eb-9378-b592b24e97b7.png)

Unfortunatly, we don't currently support chinese language models, but there is a workaround.

As stated in these 2 forums threads: 

[chinese-support](https://forum.botpress.com/t/chinese-support/4552)
[turkish-nlp-about](https://forum.botpress.com/t/turkish-nlp-about/3632)

you can download desired language models [here](https://fasttext.cc/docs/en/crawl-vectors.html) and bpe models [here](https://bpemb.h-its.org/tr/).

I strongly suggest using the biggest available models (300 dimension and 200000 vocab size) for performance reasons.

Let me know if you have any other question,

François

**Comment by franklevasseur** [comment]
Hi again,

based on [this forum thread](https://forum.botpress.com/t/chinese-support/4552/5) I assume you found a solution to your problem.

For this reason, I'll close this issue, but feel free to reopen if needed.

François

**Comment by wuguokai** [comment]
@franklevasseur Yes! Thanks a lot!
