### ISSUE TITLE
feat(nlu-server): Make the connection between Botpress and NLU stateless

### ISSUE THREAD

**Issue by charlescatta** [botpress/nlu#62]
The training state management in the current implementation of the nlu-server and the NLU module in Botpress do not allow for typical cloud deployments causing limited flexibility.

__Current behavior:__
- Each running Botpress instance must have its own dedicated instance of nlu-server running

__Expected behavior:__
- nlu-servers can be scaled from 1 to N independently from the number of running botpress/server instances
- Any nlu-server instance can receive and process any requests from any running botpress/server instance connected to the same database (NLU server bound requests can be load balanced between any nlu-server instances)

**Comment by franklevasseur** [comment]
This is a very good and valid point.

This will be my main focus for the next month.

**Comment by franklevasseur** [comment]
This PR #72 solves your issue.

**Comment by franklevasseur** [comment]
Closing as this is fixed on branch `https://github.com/botpress/nlu/pull/78`. The fix is available in binaries `1.0.0-rc.x`. The latest currently is [this one](https://github.com/botpress/nlu/releases/tag/v1.0.0-rc.3).
