### ISSUE TITLE
[BUG]: NLU Spellchecker correcting numbers

### ISSUE THREAD

**Issue by sebburon** [botpress/nlu#90]
There is an issue with the spellchecker that makes it so numbers are getting "corrected".
As an example, if I ask the user for a number and the user enters 1005.
The NLU will "correct" this number to 1000 and the saved value for the entry will be 1000.

**Comment by franklevasseur** [comment]
This is a known and very old bug that I simply didn't have time to fix. 

The spellchecker performs really badly as shown by our e2e [scores and metrics](https://github.com/botpress/nlu/blob/master/packages/e2e/current_scores/bpds-spell.json#L8). It only knows the vocabulary of the training set you train with...

My suggestions for now are:
- If you directly use the nlu-server `POST /predict` route, just don't use the spellcheck field.
- If you use the nlu server through botpress, set the `NLU_SKIP_SPELLCHECK` to true. This variable is used [here](https://github.com/botpress/botpress/blob/master/modules/nlu/src/backend/middlewares.ts#L69).

**Comment by franklevasseur** [comment]
Fixed by #119
